server:
  port: 2023
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manman_common_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huanyuan
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag # 逻辑删除属性
      logic-not-delete-value: 0 # 逻辑未删除
      logic-delete-value: 1 # 逻辑已删除
      id-type: auto
  type-aliases-package: cn.chenmanman.manmancommonsystem.model.entity # 类型别名包
  configuration:
    map-underscore-to-camel-case: true # 自动转为驼峰